### PR TITLE
handle /debug/pprof endpoints on http-metrics port

### PR DESCRIPTION
**Pull request by korniltsev**

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@korniltsev this is a duplicate of #46, isn't it?

**Comment by hairyhenderson** [comment]
Oh, I see now that you're using `godeltaprof` in addition to the regular pprof - is there a big advantage with that?

**Comment by hairyhenderson** [comment]
I've updated the branch to fit with #46, and added the delta* endpoints. Thanks!

**Review by hairyhenderson — APPROVED** [review]

**Comment by korniltsev** [comment]
> is there a big advantage with that?

There is not so big advantage for the targets, and a big advantage fro the scraper(grafana-agent)
We have some benchmarks and explanation here https://github.com/grafana/pyroscope-go/tree/main/godeltaprof

**Pull request merged**
